/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_libusb_test_app_Jaemon */

#ifndef _Included_info_libusb_test_app_Jaemon
#define _Included_info_libusb_test_app_Jaemon
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     info_libusb_test_app_Jaemon
 * Method:    exec
 * Signature: (I[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_info_libusb_test_1app_Jaemon_exec
  (JNIEnv *, jclass, jint, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
