#!/bin/sh
# Generate libusb/version_describe.h containing a LIBUSB_DESCRIBE string macro.
#
# Resolution order (single source of truth, also queried by configure.ac via
# the --classify mode below):
#   1. .git directory present → run `git describe --tags --always --dirty`.
#      Fails hard if `git` is not on PATH.
#   2. Else .tarball-version present → use its contents verbatim
#      (frozen by `make dist`).
#   3. Else → emit "Unknown source (v<MAJOR>.<MINOR>.<MICRO><RC>)" and print
#      a warning. The string is intentionally not parseable as a git
#      revision so it can be distinguished from a real build identifier.
#
# The output header is only rewritten when its content changes, so
# unchanged builds do not invalidate dependents (core.c, libusb-1.0.rc).
#
# Usage: gen-describe.sh <srcdir> <output-header>
#        gen-describe.sh --classify <srcdir>
#
# In --classify mode, prints one of "git", "tarball", "unknown" to stdout
# and exits 0; exits 1 with an error message on stderr if the source is a
# git checkout but `git' is missing.

set -e

classify() {
	srcdir="$1"
	if [ -e "$srcdir/.git" ]; then
		if ! command -v git >/dev/null 2>&1; then
			echo "gen-describe.sh: building from a git checkout but \`git' is not on PATH;" >&2
			echo "  install git or build from a release tarball." >&2
			return 1
		fi
		echo git
	elif [ -f "$srcdir/.tarball-version" ]; then
		echo tarball
	else
		echo unknown
	fi
}

if [ "$1" = "--classify" ]; then
	classify "$2"
	exit $?
fi

srcdir="$1"
out="$2"

if [ -z "$srcdir" ] || [ -z "$out" ]; then
	echo "usage: $0 <srcdir> <output-header>" >&2
	echo "       $0 --classify <srcdir>" >&2
	exit 2
fi

source_kind=$(classify "$srcdir")
describe=

case "$source_kind" in
git)
	# `safe.directory='*'` tolerates read-only / cross-ownership checkouts
	# (e.g. CI containers that mount the source as a different uid). On
	# failure we surface git's own stderr so the underlying cause is
	# visible rather than swallowed.
	describe=$(git -c safe.directory='*' -C "$srcdir" describe --tags --always --dirty 2>&1) || {
		echo "$0: \`git describe' failed in $srcdir:" >&2
		printf '%s\n' "$describe" >&2
		exit 1
	}
	if [ -z "$describe" ]; then
		echo "$0: \`git describe' produced no output in $srcdir" >&2
		exit 1
	fi
	;;
tarball)
	describe=$(tr -d '\r\n ' < "$srcdir/.tarball-version")
	;;
unknown)
	# Use POSIX BRE (\{1,\} rather than \+) so this also works under
	# BSD sed (e.g. macOS).
	version_h="$srcdir/libusb/version.h"
	major=$(sed -n 's/^#define[[:space:]]\{1,\}LIBUSB_MAJOR[[:space:]]\{1,\}\([0-9]\{1,\}\).*/\1/p' "$version_h")
	minor=$(sed -n 's/^#define[[:space:]]\{1,\}LIBUSB_MINOR[[:space:]]\{1,\}\([0-9]\{1,\}\).*/\1/p' "$version_h")
	micro=$(sed -n 's/^#define[[:space:]]\{1,\}LIBUSB_MICRO[[:space:]]\{1,\}\([0-9]\{1,\}\).*/\1/p' "$version_h")
	rc=$(sed -n 's/^#define[[:space:]]\{1,\}LIBUSB_RC[[:space:]]\{1,\}"\(-rc[0-9]*\)".*/\1/p' "$version_h")
	describe="Unknown source (v${major}.${minor}.${micro}${rc})"
	echo "$0: warning: source is neither a git checkout nor a release tarball;" >&2
	echo "  emitting LIBUSB_DESCRIBE=\"$describe\"" >&2
	;;
esac

escaped=$(printf '%s' "$describe" | sed 's/\\/\\\\/g; s/"/\\"/g')

new_content="/* Auto-generated by build-aux/gen-describe.sh. Do not edit. */
#ifndef LIBUSB_DESCRIBE
#define LIBUSB_DESCRIBE \"$escaped\"
#endif
"

if [ -f "$out" ] && [ "$(cat "$out")" = "$new_content" ]; then
	exit 0
fi

mkdir -p "$(dirname "$out")"
printf '%s' "$new_content" > "$out.tmp"
mv -f "$out.tmp" "$out"
