# Regenerates libusb/version_describe.h, providing the LIBUSB_DESCRIBE string
# baked into libusb_version::describe (see libusb.h) and the Windows .rc
# file version. Re-implements build-aux/gen-describe.sh's resolution order
# in CMake script mode so building with CMake needs neither a POSIX shell
# nor bash.exe on Windows; gen-describe.sh remains the source of truth for
# the autotools and msvc/ build paths.
#
# Usage: cmake -DSRC_DIR=<srcdir> -DOUT_FILE=<path> -P GenerateVersionDescribe.cmake
#
# Only rewrites OUT_FILE when its content changes, so unchanged builds do
# not invalidate dependents (core.c, libusb-1.0.rc).

if(NOT DEFINED SRC_DIR OR NOT DEFINED OUT_FILE)
  message(FATAL_ERROR "GenerateVersionDescribe.cmake requires -DSRC_DIR=<dir> -DOUT_FILE=<file>")
endif()

set(_describe "")

if(EXISTS "${SRC_DIR}/.git")
  find_package(Git QUIET)
  if(NOT GIT_EXECUTABLE)
    message(FATAL_ERROR
      "gen-describe: building from a git checkout but git was not found; "
      "install git or build from a release tarball.")
  endif()
  execute_process(
    COMMAND "${GIT_EXECUTABLE}" -c safe.directory=* describe --tags --always --dirty
    WORKING_DIRECTORY "${SRC_DIR}"
    OUTPUT_VARIABLE _describe
    ERROR_VARIABLE _git_error
    RESULT_VARIABLE _git_result
    OUTPUT_STRIP_TRAILING_WHITESPACE)
  if(NOT _git_result EQUAL 0 OR _describe STREQUAL "")
    message(FATAL_ERROR "gen-describe: `git describe` failed in ${SRC_DIR}: ${_git_error}")
  endif()
elseif(EXISTS "${SRC_DIR}/.tarball-version")
  file(READ "${SRC_DIR}/.tarball-version" _describe)
  string(STRIP "${_describe}" _describe)
else()
  file(READ "${SRC_DIR}/libusb/version.h" _version_h)
  string(REGEX MATCH "#define[ \t]+LIBUSB_MAJOR[ \t]+([0-9]+)" _ "${_version_h}")
  set(_major "${CMAKE_MATCH_1}")
  string(REGEX MATCH "#define[ \t]+LIBUSB_MINOR[ \t]+([0-9]+)" _ "${_version_h}")
  set(_minor "${CMAKE_MATCH_1}")
  string(REGEX MATCH "#define[ \t]+LIBUSB_MICRO[ \t]+([0-9]+)" _ "${_version_h}")
  set(_micro "${CMAKE_MATCH_1}")
  string(REGEX MATCH "#define[ \t]+LIBUSB_RC[ \t]+\"([^\"]*)\"" _ "${_version_h}")
  set(_rc "${CMAKE_MATCH_1}")
  set(_describe "Unknown source (v${_major}.${_minor}.${_micro}${_rc})")
  message(WARNING
    "gen-describe: source is neither a git checkout nor a release tarball; "
    "emitting LIBUSB_DESCRIBE=\"${_describe}\"")
endif()

string(REPLACE "\\" "\\\\" _escaped "${_describe}")
string(REPLACE "\"" "\\\"" _escaped "${_escaped}")

set(_content "/* Auto-generated by cmake/GenerateVersionDescribe.cmake. Do not edit. */
#ifndef LIBUSB_DESCRIBE
#define LIBUSB_DESCRIBE \"${_escaped}\"
#endif
")

set(_existing)
if(EXISTS "${OUT_FILE}")
  file(READ "${OUT_FILE}" _existing)
endif()

if(NOT _existing STREQUAL _content)
  get_filename_component(_out_dir "${OUT_FILE}" DIRECTORY)
  file(MAKE_DIRECTORY "${_out_dir}")
  file(WRITE "${OUT_FILE}" "${_content}")
endif()
