name: MSYS2 clang32 build
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: clang32
          update: true
          install: git mingw-w64-clang-i686-cc mingw-w64-clang-i686-autotools
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          ./bootstrap.sh
          # Disabling tests as there is some issue that prevents libtool from
          # finalizing its executable wrappers.
          # Perhaps this one https://github.com/msys2/MSYS2-packages/issues/1351
          # but it only occurs on clang32 configuration.
          ./.private/ci-build.sh --build-dir build-msys2-clang32 --no-test
